name: ClusterFuzzLite PR fuzzing
on:
  workflow_dispatch:

permissions: read-all

jobs:
  PR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Fuzzers
        uses: google/clusterfuzzlite/actions/build_fuzzers@v1

      - name: Run Fuzzer
        uses: google/clusterfuzzlite/actions/run_fuzzers@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 300
          mode: 'pr'
